### ISSUE TITLE
No gradle jar

### ISSUE THREAD

**Issue by paulzfm** [decaf-lang/decaf#1]
Some students say they cannot build the project with `gradlew`. @Harry-Chen suspects the gradle jar is missing (ignored by `.gitignore`) and maybe it's true. However, I believe `*.jar` files should be ignored because we hope students NOT submit their built jars to their repositories.

## How to fix?
Currently, **please install the lastest gradle yourself and use `gradle build` instead**.

This bug is considered in the next release.

**Comment by Harry-Chen** [comment]
You may just forcibly track the `gradle-wrapper.jar` by `git add -f`.

**Comment by Hoblovski** [comment]
Gitignore seems to ignore all jar but gradle wrapper jar, but the ignore commands are placed in a wrong order so wrapper jar is also ignored.

Fixed by 48b93e1bf7447b2bd6a7c4f22be44b4b60b96929 .
